# Generated by Django 5.2.5 on 2025-08-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='preferences/'),
        ),
    ]
