# Generated by Django 5.2.5 on 2025-08-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_preference_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='image',
        ),
    ]
